import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">DesktopOne</Link>
        </li>
        <li>
          <Link to="/desktopnine">DesktopNine</Link>
        </li>
        <li>
          <Link to="/desktopseven">DesktopSeven</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/admindashboard">Admindashboard</Link>
        </li>
        <li>
          <Link to="/admindashboardone">AdmindashboardOne</Link>
        </li>
        <li>
          <Link to="/afterlogin">AfterLogin</Link>
        </li>
        <li>
          <Link to="/payment">Payment</Link>
        </li>
        <li>
          <Link to="/studentsdataafterpayment">StudentsDataafterpayment</Link>
        </li>
        <li>
          <Link to="/institutions">Institutions</Link>
        </li>
        <li>
          <Link to="/companies">Companies</Link>
        </li>
        <li>
          <Link to="/buisness">Buisness</Link>
        </li>
        <li>
          <Link to="/institutionspage">InstitutionsPage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
